RD-884 rollback workflow epic (#226)
* added first version of workflows that wrap lifecycle operations

* added ignore failiure  parameter

* copied _make_execute_operation_graph from common

* first try for ignore failure

* add more wrappers

* flake issues

* fix_test

* flake8

* add wrapper to restart

* commit for save stuff

* removed wrap for restart

* save things

* code review fixes

* added local lifecycle and implement rollback

* handle full rollback

* update changelog

* bump version and debug logs

* removed uneccessary imports

* added rollback workflow unit tests

* fixed encoding issue

* added documentation and examples for rollback workflow

* flake 8 fixes and typo fix in plugin.yaml

* fixed notes

* fix unclear note

* add rollback workflow in the main readme

* update CI

* small fix in setup.py

* added testenv to tox

* made changlog to fit yaml conventions

* __NODOCS__

* fix mistake in states documentation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -73,6 +73,70 @@ commands:
               exit 1
             fi
 
+  validate_documentation:
+    steps:
+      - run:
+          name: "Pull Submodules"
+          command: |
+            git submodule init
+            git submodule update --remote --recursive
+      - run:
+          name: Download pip
+          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
+      - run:
+          name: Install pip
+          command: sudo python get-pip.py
+      - run:
+          name: Install virtualenv
+          command: pip install --user virtualenv
+      - run:
+          name: Init virtualenv
+          command: virtualenv env
+      - run:
+          name: install tox
+          command: pip install --user pygithub pyyaml==3.10
+      - run:
+          name: upgrade setuptools
+          command: pip install --upgrade setuptools
+      - run:
+          name: install local project
+          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
+      - attach_workspace:
+          at: workspace
+      - run: python .circleci/validate_docs.py
+
+  validate_version:
+    steps:
+      - run:
+          name: "Pull Submodules"
+          command: |
+            git submodule init
+            git submodule update --remote --recursive
+      - run:
+          name: Download pip
+          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
+      - run:
+          name: Install pip
+          command: sudo python get-pip.py
+      - run:
+          name: Install virtualenv
+          command: pip install --user virtualenv
+      - run:
+          name: Init virtualenv
+          command: virtualenv env
+      - run:
+          name: install tox
+          command: pip install --user pygithub pyyaml==3.10
+      - run:
+          name: upgrade setuptools
+          command: pip install --upgrade setuptools
+      - run:
+          name: install local project
+          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
+      - attach_workspace:
+          at: workspace
+      - run: python .circleci/validate_version.py
+
   generate_py27py36_wagon:
     steps:
       - run:
@@ -204,6 +268,16 @@ commands:
             git submodule init
             git submodule update --remote --recursive
       - run:
+          name: Set Python
+          command: |
+            if ! pyenv -v COMMAND &> /dev/null
+            then
+                echo "pyenv could not be found"
+                exit
+            else
+                pyenv global 3.6.5
+            fi
+      - run:
           name: Download pip
           command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
       - run:
@@ -228,6 +302,50 @@ commands:
           at: workspace
       - run: python .circleci/package_release.py
 
+  merge_docs:
+    steps:
+      - attach_workspace:
+          at: workspace
+      - run:
+          name: "Pull Submodules"
+          command: |
+            git submodule init
+            git submodule update --remote --recursive
+      - run:
+          name: Set Python
+          command: |
+            if ! pyenv -v COMMAND &> /dev/null
+            then
+                echo "pyenv could not be found"
+                exit
+            else
+                pyenv global 3.6.5
+            fi
+      - run:
+          name: Download pip
+          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
+      - run:
+          name: Install pip
+          command: sudo python get-pip.py
+      - run:
+          name: Install virtualenv
+          command: pip install --user virtualenv
+      - run:
+          name: Init virtualenv
+          command: virtualenv env
+      - run:
+          name: install tox
+          command: pip install --user pygithub pyyaml==3.10
+      - run:
+          name: upgrade setuptools
+          command: pip install --upgrade setuptools
+      - run:
+          name: install local project
+          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
+      - attach_workspace:
+          at: workspace
+      - run: python .circleci/merge_docs.py
+
 jobs:
 
   unittests_py27:
@@ -243,10 +361,22 @@ jobs:
       - run_unittest
 
   py3_compat:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - check_py3_compat
+
+  validate_version:
+    executor: py36
+    steps:
+      - checkout
+      - validate_version
+
+  validate_documentation:
+    executor: py36
+    steps:
+      - checkout
+      - validate_documentation
 
   wagon:
     executor: wagon_generator
@@ -281,11 +411,18 @@ jobs:
     steps:
       - checkout
       - run_integration_tests_510
+
   release:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - release_plugin
+
+  merge_docs:
+    executor: py36
+    steps:
+      - checkout
+      - merge_docs
 
 workflows:
   version: 2
@@ -294,6 +431,8 @@ workflows:
       - py3_compat
       - unittests_py27
       - unittests_py36
+      - validate_version
+      - validate_documentation
       - wagon:
           filters:
             branches:
@@ -330,8 +469,18 @@ workflows:
             - unittests_py36
             - rhel_wagon
             - wagon
+            - validate_version
+            - validate_documentation
             - integration_tests_505
             - integration_tests_510
+#      - merge_docs:
+#          filters:
+#            branches:
+#              only: /master/
+#          requires:
+#            - release
+#            - validate_documentation
+
   nightly:
     triggers:
     - schedule:
