update context, py311 wagon & remote manager

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,25 +37,48 @@ executors:
 
 commands:
 
+  setup_manager:
+    steps:
+      - run: |
+          if [[ -z "${CLOUDIFY_HOST}" ]]; then
+              exit 1
+          fi
+      - run: |
+          if [[ -z "${CLOUDIFY_TENANT}" ]] && [ -z "${CIRCLE_PROJECT_REPONAME}" ]; then
+              exit 1
+          fi
+      - run: |
+          if [[ -z "${CLOUDIFY_TOKEN}" ]]; then
+              exit 1
+          fi
+      - run: |
+          response=$(curl --write-out '%{http_code}' --silent --insecure --header "Tenant: ${CLOUDIFY_TENANT}" --header "Authentication-Token: ${CLOUDIFY_TOKEN}" https://$CLOUDIFY_HOST/api/v3.1/status --output /dev/null)
+          if [[ $response != 200 ]]; then
+              echo "Failed to get manager status";
+              exit 1
+          fi
+      - run: pip3 install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/refs/heads/master.zip
+      - run: git submodule update --init --recursive --remote
+
   prepare_test_manager:
     steps:
-      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -p $(find ~/project/workspace/build/ -name *centos-Core*x86_64.wgn)  ~/project/plugin.yaml
+      - run: ecosystem-test prepare-remote-test-manager -p $(find ~/project/workspace/build/ -name *manylinux-py311-none-linux_x86_64.wgn*)  ~/project/plugin.yaml
 
   run_cloudinit_test:
     steps:
-      - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/utilities-examples/cloudify_cloudinit/simple.yaml --test-id=cloudify_cloudinit --on-failure=uninstall-force
+      - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/utilities-examples/cloudify_cloudinit/simple.yaml --test-id=cloudify_cloudinit --on-failure=uninstall-force
 
   run_ssh_key_test:
     steps:
-      - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/utilities-examples/cloudify_ssh_key/create-secret-agent-key.yaml --test-id=cloudify_ssh_key --on-failure=uninstall-force
+      - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/utilities-examples/cloudify_ssh_key/create-secret-agent-key.yaml --test-id=cloudify_ssh_key --on-failure=uninstall-force
 
   run_secrets_test:
       steps:
-        - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/utilities-examples/cloudify_secrets/write-secret-blueprint.yaml --test-id=cloudify_secrets --on-failure=uninstall-force
+        - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/utilities-examples/cloudify_secrets/write-secret-blueprint.yaml --test-id=cloudify_secrets --on-failure=uninstall-force
 
   run_rest_test:
       steps:
-        - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/utilities-examples/cloudify_rest/example-github-status.yaml --test-id=cloudify_rest --on-failure=uninstall-force
+        - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/utilities-examples/cloudify_rest/example-github-status.yaml --test-id=cloudify_rest --on-failure=uninstall-force
 
 jobs:
 
@@ -79,11 +102,15 @@ workflows:
       - node/check_py3_compat_job
       - node/unittests_job:
           context: 
-            - slack-secrets
+            - plugins-inputs
           <<: *unittest-post-steps
       - node/validate_version_job
       - node/validate_documentation_job
       - wagonorb/wagon:
+          filters:
+            branches:
+              only: /([0-9\.]*\-build|master|dev)/
+      - wagonorb/wagon_311:
           filters:
             branches:
               only: /([0-9\.]*\-build|master|dev)/
@@ -97,13 +124,14 @@ workflows:
               only: /([0-9\.]*\-build|master|dev)/
       - integration_tests_py3:
           context: 
-            - slack-secrets
+            - plugins-inputs
           <<: *job-post-steps
           requires:
             - wagonorb/wagon
-          filters:
-            branches:
-              only: /([0-9\.]*\-build|master|dev)/
+            - wagonorb/wagon_311
+          # filters:
+          #   branches:
+          #     only: /([0-9\.]*\-build|master|dev)/
       - releaseorb/release:
           filters:
             branches:
@@ -112,6 +140,8 @@ workflows:
             - node/unittests_job
             - wagonorb/rhel_wagon
             - wagonorb/wagon
+            - wagonorb/arch64_wagon
+            - wagonorb/wagon_311
             - node/validate_version_job
             - node/validate_documentation_job
             - integration_tests_py3
@@ -128,9 +158,13 @@ workflows:
       - node/check_py3_compat_job
       - node/unittests_job:
           context: 
-            - slack-secrets
+            - plugins-inputs
           <<: *unittest-post-steps
       - wagonorb/wagon:
+          filters:
+            branches:
+              only: /([0-9\.]*\-build|master|dev)/
+      - wagonorb/wagon_311:
           filters:
             branches:
               only: /([0-9\.]*\-build|master|dev)/
@@ -138,17 +172,17 @@ workflows:
           filters:
             branches:
               only: /([0-9\.]*\-build|master|dev)/
-
       - wagonorb/rhel_wagon:
           filters:
             branches:
               only: /([0-9\.]*\-build|master|dev)/
       - integration_tests_py3:
           context: 
-            - slack-secrets
+            - plugins-inputs
           <<: *job-post-steps
           requires:
             - wagonorb/wagon
+            - wagonorb/wagon_311
           filters:
             branches:
               only: /([0-9\.]*\-build|master|dev)/
